name: Bug Report
description: Report a bug or defect in Vinyl Catalog System
title: "[BUG] "
labels: ["type: bug", "status: needs-info"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Where did you encounter this bug?
      multiple: true
      options:
        - Seller Site (Sell to Us)
        - Buyer Storefront (Buy from Us)
        - Admin Console
        - Pricing Engine
        - API/Backend
        - Database
        - External Integrations
        - Infrastructure
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system down, data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (cosmetic, workaround available)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots or videos if applicable
      placeholder: Drag and drop images here...

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: system
    attributes:
      label: System Information
      description: Provide system/browser details
      value: |
        - OS: [e.g., macOS 13.0, Windows 11]
        - Browser: [e.g., Chrome 120, Safari 17]
        - Node.js: [e.g., 18.17.0]
        - Database: [e.g., PostgreSQL 15.3]
      placeholder: Fill in relevant system information...

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround?
      placeholder: Describe any workaround if available...

  - type: dropdown
    id: regression
    attributes:
      label: Regression
      description: Did this work in a previous version?
      options:
        - "Yes - this is a regression"
        - "No - this never worked"
        - "Unknown"

  - type: input
    id: version
    attributes:
      label: Last Working Version
      description: If this is a regression, what was the last working version?
      placeholder: e.g., v0.5.2

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional details...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: What is the impact of this bug?
      options:
        - label: Blocks development
        - label: Blocks deployment
        - label: Data loss or corruption
        - label: Security vulnerability
        - label: Performance degradation
        - label: Poor user experience

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: I have included relevant error messages/logs
          required: false
