name: Feature Request
description: Suggest a new feature for Vinyl Catalog System
title: "[FEATURE] "
labels: ["type: feature", "status: needs-info"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this feature relate to?
      multiple: true
      options:
        - Seller Site (Sell to Us)
        - Buyer Storefront (Buy from Us)
        - Admin Console
        - Pricing Engine
        - API/Backend
        - Database
        - External Integrations
        - Infrastructure
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Business Domain
      description: Which business area does this feature impact?
      multiple: true
      options:
        - Pricing Strategy
        - Inventory Management
        - Seller Submissions
        - Catalog Search
        - Checkout & Payment
        - Shipping & Fulfillment
        - Notifications
        - Authentication
        - Analytics & Reporting

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a [user type], I need [feature] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this problem solved?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: List any alternative approaches...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
      value: |
        - [ ]
        - [ ]
        - [ ]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks other work)
        - High (important for upcoming release)
        - Medium (nice to have soon)
        - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work do you think this requires?
      options:
        - XS (< 1 day)
        - S (1-2 days)
        - M (3-5 days)
        - L (1-2 weeks)
        - XL (2+ weeks)
        - Unknown

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups
      placeholder: |
        - Screenshots
        - Mockups
        - Related issues
        - External references

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Will this feature introduce breaking changes?
      options:
        - label: This feature includes breaking changes

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: I have considered the impact on other components
          required: false
